name: trivia_web_service
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.21.0
